CREATE TABLE IF NOT EXISTS categories (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name VARCHAR(255));
CREATE TABLE IF NOT EXISTS mcc_codes (
                                         mcc_code NOT NULL VARHCAR(10),
                                         category_id NOT NULL REFERENCES categories(id))
);

CREATE TABLE IF NOT EXISTS subcategories (
                                       subcategory_id NOT NULL REFERENCES categories(id),
                                       parent_category_id NOT NULL REFERENCES categories(id),
                                       primary_key(first_category_id, second_category_id)
);

CREATE TABLE IF NOT EXISTS transactions (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                                      name VARCHAR(255),
                                      value INT NOT NULL,
                                      date DATE,
                                      mcc_code NOT NULL REFERENCES mcc_codes(mcc_code)
);